version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env_docker
    depends_on:
      migrations:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  migrations:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env_docker
    command: >
      sh -c "python3 manage.py migrate"

  db:
    image: postgres:latest
    env_file:
      - .env_docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: